#=====================================================#
#================= Configuration v2 ==================#
#=====================================================#

#=================== Global configuration ============#
url=about:blank
custom_capabilities=NULL
extra_capabilities=NULL

#=====================================================#
env=DEMO
DEMO.base=about:blank
DEMO.api_url=
STAG.api_url=
DEMO.soap_url=
#=====================================================#

#============== Locale Configurations ================#
locale=en_US
localization_testing=false
localization_encoding=UTF-8
language=en_US
#=====================================================#

#================ Retry configuration ================#
#number of extra retries to execute tests until pass
retry_count=0
#=====================================================#

#============== WebDriver configuration ==============#
explicit_timeout=20
#number of extra retries to start driver session and interval in seconds
init_retry_count=0
init_retry_interval=1
#=====================================================#

#======== Local Run for iOS Mobile ===============#
selenium_url=
capabilities.platformName=ios
capabilities.deviceType=phone
capabilities.browserName=Safari
capabilities.automationName=XCUITest
capabilities.udid=00008020-0005308201DA002E
#=====================================================#
